FROM golang:1 AS mod
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN GO111MODULE=on go mod download

FROM golang:1 as build
COPY --from=mod $GOCACHE $GOCACHE
COPY --from=mod $GOPATH/pkg/mod $GOPATH/pkg/mod
WORKDIR /app
COPY . .
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -o=/bin/ ./cmd/...

FROM scratch
COPY --from=build /bin/ /bin/
EXPOSE 8080
ENTRYPOINT ["/bin/web"]
